import assert from "node:assert/strict";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import test from "node:test";
import { Value } from "typebox/value";
import { aggregatePilotEvents, MetricEventSchema, readMetricEvents, recordMetricEvent, renderPilotReport, type MetricEventInput } from "../../src/core/engagement/metrics/index.ts";
const common = { schema_version: "1" as const, engagement_id: "eng", workflow_id: "flow", run_id: "run-1", timestamp: "2026-07-22T00:00:00.000Z", source: "runtime" as const, provenance: { quality: "measured" as const, method: "test runtime", source_reference: "evidence.json" }, evidence_references: ["evidence.json"], redaction_status: "reference_only" as const };
const value = (n: number | null, quality: "measured" | "estimated" | "unavailable" = "measured", unit = "count") => ({ value: n, quality, unit });
function started(): MetricEventInput { return { ...common, event_type: "run_started", payload: { mode: "shadow", issue: "1", repository: "owner/repo", commit: "a".repeat(40), engagement: "eng", start_time: common.timestamp } }; }
function completed(): MetricEventInput { return { ...common, timestamp: "2026-07-22T00:01:00.000Z", event_type: "run_completed", payload: { final_status: "completed", runtime_ms: value(60_000, "measured", "ms"), cost_accounting_status: "mixed", measured_cost_usd: value(1, "measured", "usd"), estimated_cost_usd: value(2, "estimated", "usd"), reserved_exposure_usd: value(3, "estimated", "usd"), model_call_count: value(1), tool_call_count: value(null, "unavailable"), retry_count: value(0), timeout: false, cancellation: false, safety_status: "passed", validation_status: "passed" } }; }
test("closed schema rejects unknown fields and invalid measured values", () => { const event = { ...started(), event_id: "a".repeat(64) }; assert.equal(Value.Check(MetricEventSchema, event), true); assert.equal(Value.Check(MetricEventSchema, { ...event, surprise: true }), false); assert.equal(Value.Check(MetricEventSchema, { ...event, provenance: { ...event.provenance, quality: "guessed" } }), false); assert.equal(Value.Check(MetricEventSchema, { ...completed(), event_id: "b".repeat(64), payload: { ...completed().payload, runtime_ms: value(-1, "measured", "ms") } }), false); });
test("append is deterministic, idempotent, ordered, isolated, and detects corruption", () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), "agentify-metrics-")); const first = recordMetricEvent(root, completed()); recordMetricEvent(root, started()); assert.equal(recordMetricEvent(root, completed()).created, false); assert.deepEqual(readMetricEvents(root, "eng").map((e) => e.event_type), ["run_started", "run_completed"]); assert.equal(readMetricEvents(root, "other").length, 0); fs.appendFileSync(path.join(root, "engagements/eng/metrics/run-events.jsonl"), "{"); assert.throws(() => readMetricEvents(root, "eng"), /incomplete JSONL append/); assert.equal(first.event.event_id.length, 64); });
test("metric stream symlink escapes are rejected", () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), "agentify-metrics-link-")); const outside = path.join(root, "outside"); fs.writeFileSync(outside, ""); const directory = path.join(root, "engagements/eng/metrics"); fs.mkdirSync(directory, { recursive: true }); fs.symlinkSync(outside, path.join(directory, "run-events.jsonl")); assert.throws(() => recordMetricEvent(root, started()), /cannot be a symlink/); });
test("aggregates preserve missing values and separate measured, estimated, and exposure", () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), "agentify-metrics-")); recordMetricEvent(root, started()); recordMetricEvent(root, completed()); const aggregate = aggregatePilotEvents(readMetricEvents(root, "eng")); assert.equal(aggregate.runs.completion_rate, 1); assert.equal(aggregate.runtime_ms.p50, 60_000); assert.equal(aggregate.runtime_ms.p95, 60_000); assert.equal(aggregate.costs.measured_usd, 1); assert.equal(aggregate.costs.estimated_usd, 2); assert.match(aggregate.sample_warning!, /small sample/); assert.equal(JSON.stringify(aggregate).includes("reserved_exposure"), false); });
test("empty report is factual and contains no fabricated success conclusion", () => { const report = renderPilotReport({ engagement_id: "eng", workflow_name: "Flow" } as never, []); assert.match(report, /no_pilot_data/); assert.match(report, /does not prove ROI/); assert.doesNotMatch(report, /ROI proven|Ready to scale|Business value proven/); });
