import assert from "node:assert/strict";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import test from "node:test";
import { Value } from "typebox/value";
import { AUTONOMY_LEVELS, PromotionStateSchema, appendPromotionRecord, assertEngagementPromotable, assertPromotionTransition, createEngagement, createPromotionState, currentAutonomyLevel, evaluatePromotion, promotionStatePath, readEngagement, readPromotionState, renderPromotionReport, revokePromotion, type PromotionActuals, type PromotionPolicy, type PromotionRecord } from "../../src/core/engagement/index.ts";
import { writeEngagementJsonAtomic } from "../../src/core/engagement/state.ts";

const timestamp = "2026-07-22T00:00:00.000Z";
const conditions = { minimum_eligible_tasks: 10, minimum_pass_at_1: 0.9, minimum_repeated_run_consistency: 0.8, maximum_major_rework_rate: 0.1, maximum_forbidden_action_failures: 0, maximum_security_failures: 0, maximum_cost_usd: 20, maximum_runtime_ms: 60_000, required_human_reviews: 2, required_business_owner: "Business Owner", required_technical_owner: "Technical Owner", required_rollback_test: true, required_escalation_test: true, required_monitoring: true, required_risk_register_status: "accepted", required_approval_checkpoint: true, no_unresolved_critical_risks: true } as const;
const actuals: PromotionActuals = { eligible_tasks: 10, pass_at_1: 0.9, repeated_run_consistency: 0.8, major_rework_rate: 0.1, forbidden_action_failures: 0, security_failures: 0, cost_usd: 20, runtime_ms: 60_000, human_reviews: 2, business_owner: "Business Owner", technical_owner: "Technical Owner", rollback_test_passed: true, escalation_test_passed: true, monitoring_active: true, risk_register_status: "accepted", approval_checkpoint_passed: true, unresolved_critical_risks: 0 };
function policy(overrides: Partial<PromotionPolicy> = {}): PromotionPolicy { return { schema_version: "1", policy_version: "eng-v1", engagement_id: "eng", workflow_id: "workflow", execution_policy_mode: "review-readonly", current_level: "observe", candidate_level: "draft", requested_by: "Requester", evidence_run_ids: ["run-1"], required_conditions: conditions, review_at: "2026-08-22T00:00:00.000Z", rollback_level: "observe", ...overrides }; }

test("every autonomy level is represented without claiming runtime support", () => { assert.deepEqual(AUTONOMY_LEVELS, ["observe", "draft", "approved_execute", "bounded_auto", "policy_auto"]); });
test("valid adjacency is accepted and skipped, reverse, same, and policy_auto transitions are rejected", () => { assert.doesNotThrow(() => assertPromotionTransition("observe", "draft")); assert.doesNotThrow(() => assertPromotionTransition("draft", "approved_execute")); assert.doesNotThrow(() => assertPromotionTransition("approved_execute", "bounded_auto")); for (const pair of [["observe", "approved_execute"], ["draft", "draft"], ["draft", "observe"], ["bounded_auto", "policy_auto"]] as const) assert.throws(() => assertPromotionTransition(pair[0], pair[1])); });
test("missing evidence is insufficient and boundary values pass exactly", () => { const missing = evaluatePromotion(policy(), { ...actuals, pass_at_1: undefined }, timestamp, "Approver"); assert.equal(missing.decision, "insufficient_evidence"); assert.deepEqual(missing.missing_evidence, ["minimum_pass_at_1"]); const boundary = evaluatePromotion(policy(), actuals, timestamp, "Approver"); assert.equal(boundary.decision, "rejected"); assert.deepEqual(boundary.passed_requirements.sort(), Object.keys(conditions).sort()); assert.ok(boundary.failed_requirements.includes("candidate_level_supported")); });
test("failed safety conditions always block promotion", () => { const record = evaluatePromotion(policy(), { ...actuals, security_failures: 1 }, timestamp, "Approver"); assert.equal(record.decision, "rejected"); assert.ok(record.safety_blockers.includes("maximum_security_failures")); });
test("human approval is required and no model approval fallback exists", () => { const record = evaluatePromotion(policy(), actuals, timestamp); assert.equal(record.decision, "insufficient_evidence"); assert.ok(record.missing_evidence.includes("human_approval")); assert.equal(record.approved_by, null); });
test("expiration is explicit and safely resolves to rollback", () => { const expired = evaluatePromotion(policy({ expires_at: "2026-07-21T00:00:00.000Z" }), actuals, timestamp, "Approver"); assert.equal(expired.decision, "expired"); const approved = { ...expired, decision: "approved" as const, expires_at: "2026-07-21T00:00:00.000Z" }; const state = { ...createPromotionState(policy()), records: [approved] }; assert.equal(currentAutonomyLevel(state, new Date(timestamp)), "observe"); });
test("append-only persistence preserves audit records and detects concurrent revisions", () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), "promotion-")); const state = createPromotionState(policy()); writeEngagementJsonAtomic(promotionStatePath(root, "eng"), state); const record = evaluatePromotion(policy(), actuals, timestamp, "Approver"); const next = appendPromotionRecord(root, state, record, 1); assert.equal(next.records.length, 1); assert.throws(() => appendPromotionRecord(root, state, { ...record, record_id: "different" }, 1), /revision conflict/); assert.deepEqual(readPromotionState(root, "eng").records, [record]); });
test("revocation appends history and derives the configured rollback level", () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), "promotion-revoke-")); const base = createPromotionState(policy()); const approved: PromotionRecord = { ...evaluatePromotion(policy(), actuals, timestamp, "Approver"), decision: "approved", failed_requirements: [], reasons: ["fixture approval"] }; const state = { ...base, revision: 2, records: [approved] }; writeEngagementJsonAtomic(promotionStatePath(root, "eng"), state); const revoked = revokePromotion(root, state, "Owner", "2026-07-23T00:00:00.000Z", "Safety review"); assert.equal(revoked.records.length, 2); assert.equal(revoked.records[1]?.decision, "revoked"); assert.equal(currentAutonomyLevel(revoked), "observe"); });
test("promotion schema is strict and report output is deterministic", () => { const state = createPromotionState(policy()); assert.equal(Value.Check(PromotionStateSchema, state), true); assert.equal(Value.Check(PromotionStateSchema, { ...state, surprise: true }), false); assert.equal(renderPromotionReport(state), renderPromotionReport(state)); assert.match(renderPromotionReport(state), /GitHub behavior/); });
test("terminal engagements cannot be evaluated for promotion", () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), "promotion-terminal-")); createEngagement(root, "eng", { repository: { root, remote: null }, workflow_name: "Workflow", workflow_owner: "Owner", intended_users: ["user"], systems_involved: ["system"], problem_statement: "Problem", workflow_frequency: "daily", baseline_metrics: [{ name: "time", unit: "minutes", value: 1 }], desired_primary_outcome: "Outcome", target: { direction: "decrease", value: 0, unit: "minutes" }, guardrail_metrics: [], forbidden_actions: [], requires_human_approval: true, business_owner: "Business", technical_owner: "Technical", evidence_references: [] }, { now: () => new Date(timestamp) }); const charter = readEngagement(root, "eng"); writeEngagementJsonAtomic(path.join(root, "engagements", "eng", "charter.json"), { ...charter, status: "completed" }); assert.throws(() => assertEngagementPromotable(root, "eng"), /terminal engagement/); });
