import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { readJson, reconcileModelCall, reserveModelCall, requestCancellation, writeAtomic } from "../scripts/draft-run-control.mjs";

export default function draftBudget(pi: ExtensionAPI) {
  const stateFile = process.env.AGENTIFY_DRAFT_STATE_FILE; const configFile = process.env.AGENTIFY_DRAFT_CONFIG_FILE; const step = process.env.AGENTIFY_DRAFT_STEP ?? "model call";
  if (!stateFile || !configFile) throw new Error("draft budget state/configuration is required");
  const config = readJson(configFile, "draft configuration"); let activeCall: string | null = null; let requestId: string | null = null; let deadlineTimer: NodeJS.Timeout | null = null;
  pi.on("session_start", async (_event, ctx) => { if (!ctx.model) throw new Error("model is unavailable"); const max = config.maximum_output_tokens; if (!Number.isInteger(max) || max < 1) throw new Error("maximum_output_tokens is invalid"); await pi.setModel({ ...ctx.model, maxTokens: Math.min(ctx.model.maxTokens, max) }); });
  pi.on("turn_start", (_event, ctx) => { const state = readJson(stateFile); const model = ctx.model; if (!model) throw new Error("model is unavailable"); const call = reserveModelCall(state, config, { step, provider: model.provider, model: model.id, maximum_input_tokens: config.maximum_input_tokens, maximum_output_tokens: Math.min(model.maxTokens, config.maximum_output_tokens) }); activeCall = call.call_id; writeAtomic(stateFile, state); const remaining = Date.parse(state.runtime.deadline_at) - Date.now(); deadlineTimer = setTimeout(() => { const current = readJson(stateFile); requestCancellation(current, step, Date.now(), true); current.runtime.remote_model_cancellation_acknowledged = false; writeAtomic(stateFile, current); ctx.abort(); }, Math.max(1, remaining)); });
  pi.on("after_provider_response", (event) => { requestId = event.headers["request-id"] ?? event.headers["x-request-id"] ?? null; });
  pi.on("message_end", (event) => { if (event.message.role !== "assistant" || !activeCall) return; if (deadlineTimer) clearTimeout(deadlineTimer); const usage = event.message.usage; const state = readJson(stateFile); reconcileModelCall(state, config, activeCall, usage ? { input_tokens: usage.input, cached_input_tokens: usage.cacheRead, cache_write_input_tokens: usage.cacheWrite, output_tokens: usage.output, reasoning_tokens: usage.reasoning ?? null, total_tokens: usage.totalTokens, provider_request_id: requestId } : null); if (state.runtime.cancellation_requested_at) state.runtime.remote_model_cancellation_acknowledged = event.message.stopReason === "aborted"; writeAtomic(stateFile, state); activeCall = null; requestId = null; });
  pi.on("agent_settled", () => { if (deadlineTimer) clearTimeout(deadlineTimer); const state = readJson(stateFile); if (state.runtime.cancellation_requested_at && !state.runtime.cancellation_completed_at) { state.runtime.cancellation_completed_at = new Date().toISOString(); writeAtomic(stateFile, state); } });
}
