import type { MetricEvent } from "./schema.ts";

export interface PilotAggregates { schema_version: "1"; sample_warning: string | null; runs: { total: number; shadow: number; draft: number; completed: number; completion_rate: number | null; failure_rate: number | null; cancellations: number; timeouts: number; safety_failures: number }; escalation_count: number; costs: { measured_usd: number | null; measured_sample_size: number; estimated_usd: number | null; estimated_sample_size: number }; runtime_ms: Summary; time_to_plan_ms: Summary; time_to_draft_ms: Summary; review_minutes: Summary; acceptance_counts: Record<string, number>; major_rework_rate: number | null; rejection_rate: number | null; intervention_count: number; repeat_use_count: number }
interface Summary { sample_size: number; p50: number | null; p95: number | null }
function percentile(values: number[], percentileValue: number): number | null { if (!values.length) return null; const sorted = [...values].sort((a, b) => a - b); return sorted[Math.ceil((percentileValue / 100) * sorted.length) - 1]!; }
function summary(values: number[]): Summary { return { sample_size: values.length, p50: percentile(values, 50), p95: percentile(values, 95) }; }
function present(field: { value: number | null; quality: string }): number[] { return field.value === null || field.quality === "unavailable" ? [] : [field.value]; }
export function aggregatePilotEvents(events: readonly MetricEvent[]): PilotAggregates {
  const starts = events.filter((e) => e.event_type === "run_started"); const completions = events.filter((e) => e.event_type === "run_completed"); const reviews = events.filter((e) => e.event_type === "human_review_recorded");
  const acceptance: Record<string, number> = {}; for (const review of reviews) acceptance[review.payload.outcome] = (acceptance[review.payload.outcome] ?? 0) + 1;
  const measured = completions.flatMap((e) => e.payload.measured_cost_usd.quality === "measured" ? present(e.payload.measured_cost_usd) : []); const estimated = completions.flatMap((e) => e.payload.estimated_cost_usd.quality === "estimated" ? present(e.payload.estimated_cost_usd) : []);
  const rate = (count: number, total: number) => total ? count / total : null; const failed = completions.filter((e) => e.payload.final_status === "failed" || e.payload.final_status === "rejected").length;
  return { schema_version: "1", sample_warning: starts.length < 5 ? `small sample: ${starts.length} run(s); do not infer business outcomes` : null, runs: { total: starts.length, shadow: starts.filter((e) => e.payload.mode === "shadow").length, draft: starts.filter((e) => e.payload.mode === "draft").length, completed: completions.filter((e) => e.payload.final_status === "completed").length, completion_rate: rate(completions.filter((e) => e.payload.final_status === "completed").length, starts.length), failure_rate: rate(failed, starts.length), cancellations: completions.filter((e) => e.payload.cancellation).length, timeouts: completions.filter((e) => e.payload.timeout).length, safety_failures: completions.filter((e) => e.payload.safety_status === "failed").length }, escalation_count: events.filter((e) => e.event_type === "readiness_recorded").reduce((n, e) => n + e.payload.escalations.length, 0), costs: { measured_usd: measured.length ? measured.reduce((a, b) => a + b, 0) : null, measured_sample_size: measured.length, estimated_usd: estimated.length ? estimated.reduce((a, b) => a + b, 0) : null, estimated_sample_size: estimated.length }, runtime_ms: summary(completions.flatMap((e) => present(e.payload.runtime_ms))), time_to_plan_ms: summary(events.filter((e) => e.event_type === "plan_recorded").flatMap((e) => present(e.payload.time_to_first_plan_ms))), time_to_draft_ms: summary(events.filter((e) => e.event_type === "draft_published").flatMap((e) => present(e.payload.time_to_draft_ms))), review_minutes: summary(reviews.flatMap((e) => present(e.payload.review_minutes))), acceptance_counts: acceptance, major_rework_rate: rate(acceptance.major_rework ?? 0, reviews.length), rejection_rate: rate(acceptance.rejected ?? 0, reviews.length), intervention_count: events.filter((e) => e.event_type === "intervention_recorded").length, repeat_use_count: events.filter((e) => e.event_type === "adoption_recorded" && e.payload.repeated_use).length };
}
