import type { EngagementCharter } from "../schema/engagement-charter.ts";
import { aggregatePilotEvents } from "./aggregate.ts";
import type { MetricEvent } from "./schema.ts";
export function renderPilotReport(charter: EngagementCharter, events: readonly MetricEvent[]): string {
  const a = aggregatePilotEvents(events); const dates = events.map((e) => e.timestamp).sort(); const reviews = events.filter((e) => e.event_type === "human_review_recorded"); const incidents = events.filter((e) => e.event_type === "incident_recorded"); const baselines = events.filter((e) => e.event_type === "baseline_recorded");
  const conclusion = !events.length ? "no_pilot_data" : a.runs.safety_failures || incidents.some((e) => e.payload.severity === "critical" && e.payload.status !== "resolved") ? "safety_blocked" : a.runs.total < 5 ? "insufficient_sample" : reviews.length < a.runs.draft ? "human_review_incomplete" : "collecting_data";
  const fmt = (value: number | null) => value === null ? "unavailable" : String(value); const provenance = [...new Set(events.map((e) => `${e.provenance.quality}: ${e.provenance.method}`))].sort();
  return `# Pilot report\n\nEngagement: ${charter.engagement_id}\nWorkflow: ${charter.workflow_name}\nPilot period: ${dates.length ? `${dates[0]} to ${dates.at(-1)}` : "no data"}\nConclusion: ${conclusion}\n\n## Data provenance\n${provenance.length ? provenance.map((v) => `- ${v}`).join("\n") : "- unavailable"}\n\n## Baseline data\n- records: ${baselines.length}\n\n## Shadow runs\n- count: ${a.runs.shadow}\n\n## Draft runs\n- count: ${a.runs.draft}\n\n## Runtime\n- p50 ms: ${fmt(a.runtime_ms.p50)}\n- p95 ms: ${fmt(a.runtime_ms.p95)}\n- sample size: ${a.runtime_ms.sample_size}\n\n## Cost\n- measured USD: ${fmt(a.costs.measured_usd)} (n=${a.costs.measured_sample_size})\n- estimated USD: ${fmt(a.costs.estimated_usd)} (n=${a.costs.estimated_sample_size})\n- reserved exposure is not spend and is not aggregated as cost\n\n## Quality outcomes\n- completions: ${a.runs.completed}/${a.runs.total}\n- safety failures: ${a.runs.safety_failures}\n\n## Human reviews\n- records: ${reviews.length}\n- major-rework rate: ${fmt(a.major_rework_rate)}\n- rejection rate: ${fmt(a.rejection_rate)}\n\n## Interventions\n- count: ${a.intervention_count}\n\n## Incidents\n- count: ${incidents.length}\n\n## Adoption observations\n- repeat-use records: ${a.repeat_use_count}\n\n## Missing evidence\n${a.runs.total === 0 ? "- runtime pilot evidence\n- human review evidence\n- adoption evidence" : "- fields marked unavailable remain missing and are never treated as zero"}\n\n## Small-sample warnings\n- ${a.sample_warning ?? "none recorded; sample size alone does not prove causality or business value"}\n\n## Open risks\n- This instrumentation does not prove ROI, business value, product-market fit, readiness to scale, or readiness for autonomous operation.\n- Repeated real pilots and a separate productization review remain required.\n`;
}
