#!/usr/bin/env node

import { build } from "esbuild";
import { spawnSync } from "node:child_process";
import * as crypto from "node:crypto";
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const distDir = path.join(repoRoot, "dist");
const rootPackage = JSON.parse(fs.readFileSync(path.join(repoRoot, "package.json"), "utf8"));
/** Actual module inputs esbuild pulled into each installed runtime. */
const bundleInputs = new Map();

// A version string alone cannot distinguish two builds of the same version, so
// every build stamps the exact source it came from.
function gitOutput(...args) {
  const result = spawnSync("git", ["-C", repoRoot, ...args], { encoding: "utf8" });
  return result.status === 0 ? result.stdout.trim() : null;
}
const sourceCommit = gitOutput("rev-parse", "HEAD");
const sourceDirty = sourceCommit === null
  ? null
  : gitOutput("status", "--porcelain") !== "";
const piSdkPackage = JSON.parse(fs.readFileSync(
  path.join(repoRoot, "node_modules", "@earendil-works", "pi-coding-agent", "package.json"),
  "utf8",
));
if (!/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(piSdkPackage.version ?? "")) {
  throw new Error("installed pi-coding-agent package has no valid semantic version");
}
const createRequireBanner =
  `import { createRequire as __agentifyCreateRequire } from "node:module"; const require = __agentifyCreateRequire(import.meta.url);`;

// The two runtimes are committed into the target repository, where ordinary
// whole-repository scanners will read them as source. A bundled dependency
// graph cannot satisfy an arbitrary repository's lint rules, so the generated
// artifact opts itself out inline rather than requiring the repository to
// weaken or edit its own configuration.
const generatedArtifactBanner = [
  "/* eslint-disable */",
  "/* istanbul ignore file */",
  "// @ts-nocheck",
  "// Generated by Agentify. Do not edit. See .github/agentify/runtime-inventory.json.",
].join("\n");
const MAX_RUNTIME_FILE_BYTES = 15 * 1024 * 1024;
const MAX_RUNTIME_TOTAL_BYTES = 24 * 1024 * 1024;

fs.rmSync(distDir, { recursive: true, force: true });
fs.mkdirSync(distDir, { recursive: true });

for (const entry of [
  {
    source: path.join(repoRoot, "src", "cli.ts"),
    outfile: path.join(distDir, "cli.js"),
    installedRuntime: false,
  },
  {
    source: path.join(repoRoot, "src", "core", "learning", "cli.ts"),
    outfile: path.join(distDir, "learning-runtime.mjs"),
    installedRuntime: true,
  },
  {
    source: path.join(repoRoot, "src", "core", "task-lifecycle", "cli.ts"),
    outfile: path.join(distDir, "task-runtime.mjs"),
    installedRuntime: true,
  },
]) {
  const result = await build({
    metafile: entry.installedRuntime,
    entryPoints: [entry.source],
    outfile: entry.outfile,
    bundle: true,
    platform: "node",
    format: "esm",
    target: "node22",
    banner: {
      js: entry.installedRuntime
        ? `${generatedArtifactBanner}\n${createRequireBanner}`
        : createRequireBanner,
    },
    sourcemap: false,
    legalComments: "none",
    minifySyntax: entry.installedRuntime,
    minifyWhitespace: entry.installedRuntime,
    logLevel: "info",
    define: {
      __AGENTIFY_BUNDLED_PI_SDK_VERSION__: JSON.stringify(piSdkPackage.version),
      __AGENTIFY_SOURCE_COMMIT__: JSON.stringify(sourceCommit),
      __AGENTIFY_SOURCE_DIRTY__: JSON.stringify(sourceDirty),
    },
  });
  if (entry.installedRuntime) bundleInputs.set(path.basename(entry.outfile), Object.keys(result.metafile.inputs));
}

const assetCopies = [
  [path.join(repoRoot, "src", "core", "audit", "prompts"), path.join(distDir, "prompts")],
];

for (const [source, destination] of assetCopies) {
  if (!fs.existsSync(source)) {
    throw new Error(`Required runtime asset directory is missing: ${source}`);
  }
  fs.cpSync(source, destination, { recursive: true, force: true });
}

const runtimeInventory = ["learning-runtime.mjs", "task-runtime.mjs"].map((name) => {
  const filePath = path.join(distDir, name);
  const content = fs.readFileSync(filePath);
  return {
    path: name,
    bytes: content.length,
    sha256: crypto.createHash("sha256").update(content).digest("hex"),
  };
});
const totalRuntimeBytes = runtimeInventory.reduce((sum, entry) => sum + entry.bytes, 0);
for (const entry of runtimeInventory) {
  if (entry.bytes > MAX_RUNTIME_FILE_BYTES) {
    throw new Error(`${entry.path} exceeds the ${MAX_RUNTIME_FILE_BYTES}-byte installed-runtime budget`);
  }
}
if (totalRuntimeBytes > MAX_RUNTIME_TOTAL_BYTES) {
  throw new Error(`installed runtimes total ${totalRuntimeBytes} bytes, above the ${MAX_RUNTIME_TOTAL_BYTES}-byte budget`);
}
// The inventory is derived from esbuild's own input graph, so it lists what the
// bundles actually contain. Walking package manifests instead would include
// dependencies no bundle reached, miss anything resolved another way, and
// collapse two versions of the same package into one entry.
function packageRootFor(inputPath) {
  const segments = inputPath.split("/");
  let index = segments.lastIndexOf("node_modules");
  if (index < 0) return null;
  let end = index + 2;
  if (segments[index + 1]?.startsWith("@")) end += 1;
  return { root: segments.slice(0, end).join("/"), name: segments.slice(index + 1, end).join("/") };
}

function bundledDependencies() {
  // Keyed by resolved root, so two versions of one package stay distinct.
  const byRoot = new Map();
  for (const [bundle, inputs] of bundleInputs) {
    for (const input of inputs) {
      const resolved = packageRootFor(input);
      if (resolved === null) continue;
      const manifestPath = path.join(repoRoot, resolved.root, "package.json");
      if (!fs.existsSync(manifestPath)) continue;
      const existing = byRoot.get(resolved.root);
      if (existing) {
        existing.bundles.add(bundle);
        continue;
      }
      const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf-8"));
      byRoot.set(resolved.root, {
        name: resolved.name,
        version: manifest.version ?? null,
        license: manifest.license
          ?? (Array.isArray(manifest.licenses) ? manifest.licenses.map((entry) => entry.type).join(" OR ") : null),
        resolved_root: resolved.root,
        bundles: new Set([bundle]),
      });
    }
  }
  return [...byRoot.values()]
    .map((entry) => ({ ...entry, bundles: [...entry.bundles].sort() }))
    .sort((left, right) =>
      left.name.localeCompare(right.name) || String(left.version).localeCompare(String(right.version)));
}

const LICENSE_FILE_NAMES = ["LICENSE", "LICENSE.md", "LICENSE.txt", "LICENCE", "LICENCE.md", "COPYING", "NOTICE"];

/**
 * Several common licenses require the license text and copyright notice to
 * travel with redistributed code. The bundles strip comments, so the notices
 * are emitted alongside them instead.
 */
function thirdPartyNotices(dependencies) {
  const sections = [
    "# Third-party notices",
    "",
    "Agentify's installed runtimes embed the packages below. Each entry lists the",
    "license text found in that package where one is present.",
    "",
  ];
  const missing = [];
  for (const dependency of dependencies) {
    sections.push(`## ${dependency.name}@${dependency.version ?? "unknown"} (${dependency.license ?? "no license field"})`, "");
    const found = LICENSE_FILE_NAMES
      .map((name) => path.join(repoRoot, dependency.resolved_root, name))
      .find((candidate) => fs.existsSync(candidate));
    if (found === undefined) {
      missing.push(`${dependency.name}@${dependency.version ?? "unknown"}`);
      sections.push("_No license file is distributed with this package._", "");
      continue;
    }
    // Upstream license files carry mixed line endings; the packaged tree is LF.
    const licenseText = fs.readFileSync(found, "utf-8").replace(/\r\n?/g, "\n").trimEnd();
    sections.push("```text", licenseText, "```", "");
  }
  return { text: `${sections.join("\n")}\n`, missing };
}

const dependencies = bundledDependencies();
const unlicensed = dependencies.filter((entry) => !entry.license).map((entry) => entry.name);
if (unlicensed.length > 0) {
  throw new Error(`bundled dependencies declare no license: ${unlicensed.join(", ")}`);
}
const notices = thirdPartyNotices(dependencies);
fs.writeFileSync(path.join(distDir, "THIRD_PARTY_NOTICES.md"), notices.text);
fs.writeFileSync(path.join(distDir, "runtime-inventory.json"), `${JSON.stringify({
  schema_version: "3",
  agentify_version: rootPackage.version,
  source_commit: sourceCommit,
  source_dirty: sourceDirty,
  pi_sdk_version: piSdkPackage.version,
  node_engine: rootPackage.engines?.node ?? null,
  files: runtimeInventory,
  bundled_dependencies: dependencies,
  third_party_notices: {
    path: "THIRD_PARTY_NOTICES.md",
    sha256: crypto.createHash("sha256").update(notices.text).digest("hex"),
    packages_without_license_text: notices.missing,
  },
}, null, 2)}\n`);

for (const required of [
  path.join(distDir, "cli.js"),
  path.join(distDir, "learning-runtime.mjs"),
  path.join(distDir, "task-runtime.mjs"),
  path.join(distDir, "runtime-inventory.json"),
  path.join(distDir, "THIRD_PARTY_NOTICES.md"),
  path.join(distDir, "prompts", "builder.md"),
]) {
  if (!fs.existsSync(required)) throw new Error(`Build output is missing: ${required}`);
}

console.log("compiled distribution written to dist/");
