// subagent-registry.ts — the SubagentRegistry for the orchestrator.
//
// Discovers the feature agents generated by the audit and the
// user-level agent templates managed by standalone agentify. Adds
// the fields the orchestrator needs:
//
//   domain: string[] | null        — reserved for Grade 2 (domain lock)
//   expertise: string | null       — path to expertise.md (Grade 2 ACT->LEARN)
//   color: string                  — TUI color (white default)
//   system_prompt_inline: boolean  — when true, file body overrides the registry's
//
// New fields are optional; missing fields default to sensible values
// so existing `.pi/agents/*.md` files keep working.

import * as fs from "node:fs";
import * as path from "node:path";
import {
  parseFrontmatter,
} from "@earendil-works/pi-coding-agent";
import { defaultConfigDir } from "../agentify-config.ts";

/**
 * Allowed model choices for the frontmatter. `inherit` (the
 * default) means the orchestrator's parent agent decides. We
 * mirror the lessons' `modelAliases` table.
 */
export const MODEL_CHOICES = ["inherit", "haiku", "sonnet", "opus"] as const;
export type ModelChoiceLiteral = (typeof MODEL_CHOICES)[number];

export interface AgentFrontmatter {
  name: string;
  description: string;
  tools: string[];
  model: ModelChoiceLiteral;
  /**
   * Named slot role for this sub-agent. Defaults to "primary"
   * when unset. See `ModelRole`.
   */
  modelRole?: "primary" | "explorer" | "lite";
  domain: string[] | null;
  expertise: string | null;
  color: string;
  /** When true, the system prompt body is the authoritative
   *  content (the registry supplies only metadata). */
  system_prompt_inline: boolean;
}

export interface AgentDefinition extends AgentFrontmatter {
  /** Path the agent was loaded from (absolute). */
  filePath: string;
  /** Source tier: user-level or project-level. */
  source: "user" | "project";
  /** The full markdown body (frontmatter stripped). */
  systemPrompt: string;
}

/**
 * Parse just the frontmatter block from raw markdown. Returns
 * normalized defaults for missing fields. Empty tools list means
 * "inherit the orchestrator's allowed tools, filtered to safe
 * defaults" (read-only by default in the base runtime).
 */
export function parseAgentFrontmatter(raw: string, filePath: string): {
  frontmatter: AgentFrontmatter;
  body: string;
} | null {
  let parsed: { frontmatter: Record<string, unknown>; body: string };
  try {
    parsed = parseFrontmatter<Record<string, unknown>>(raw);
  } catch {
    return null;
  }
  const fm = parsed.frontmatter;
  const name = stringify(fm["name"]).trim();
  const description = stringify(fm["description"]).trim();
  if (!name) return null;
  if (!description) return null;

  // tools: comma-separated string OR YAML list.
  const tools = parseStringList(fm["tools"]);

  const modelRaw = stringify(fm["model"]).trim().toLowerCase() || "inherit";
  const model: ModelChoiceLiteral = (MODEL_CHOICES as readonly string[]).includes(modelRaw)
    ? (modelRaw as ModelChoiceLiteral)
    : "inherit";

  // domain: comma-separated path globs OR YAML list.
  const domain = parseStringListOrNull(fm["domain"]);

  const expertiseRaw = stringify(fm["expertise"]).trim();
  const expertise = expertiseRaw || null;
  const color = stringify(fm["color"]).trim() || "white";
  const systemPromptInline = parseBool(fm["system_prompt_inline"]);

  return {
    frontmatter: {
      name,
      description,
      tools,
      model,
      domain,
      expertise,
      color,
      system_prompt_inline: systemPromptInline,
    },
    body: parsed.body,
  };
}

/** Coerce any value to a string. */
function stringify(v: unknown): string {
  if (v === null || v === undefined) return "";
  if (typeof v === "string") return v;
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  if (Array.isArray(v)) return v.map((x) => String(x)).join(",");
  return "";
}

/**
 * Parse a string list. Accepts:
 *   - "a, b, c"          (comma-separated)
 *   - ["a", "b", "c"]    (YAML list)
 *   - "" / undefined / [] → []
 *   - "a"                → ["a"]
 */
function parseStringList(v: unknown): string[] {
  if (v === null || v === undefined) return [];
  if (Array.isArray(v)) {
    return v.map((x) => stringify(x).trim()).filter(Boolean);
  }
  const s = stringify(v).trim();
  if (!s) return [];
  return s.split(",").map((x) => x.trim()).filter(Boolean);
}

/**
 * Like parseStringList but returns null when empty.
 */
function parseStringListOrNull(v: unknown): string[] | null {
  const list = parseStringList(v);
  return list.length === 0 ? null : list;
}

function parseBool(v: unknown): boolean {
  if (typeof v === "boolean") return v;
  const s = stringify(v).trim().toLowerCase();
  return s === "true" || s === "yes" || s === "1" || s === "on";
}

/**
 * Load a single agent file. Returns null if the file is missing,
 * unparseable, or has invalid frontmatter.
 */
export function loadAgentFile(filePath: string, source: "user" | "project"): AgentDefinition | null {
  let content: string;
  try {
    content = fs.readFileSync(filePath, "utf-8");
  } catch {
    return null;
  }
  const parsed = parseAgentFrontmatter(content, filePath);
  if (!parsed) return null;
  return {
    ...parsed.frontmatter,
    systemPrompt: parsed.body,
    filePath,
    source,
  };
}

function isDirectory(p: string): boolean {
  try {
    return fs.statSync(p).isDirectory();
  } catch {
    return false;
  }
}

/**
 * Scan one directory for agent files. Returns the loaded agents
 * and any errors encountered. Errors are non-fatal: the scan
 * continues.
 */
export function loadAgentsFromDir(
  dir: string,
  source: "user" | "project",
): { agents: AgentDefinition[]; errors: string[] } {
  const agents: AgentDefinition[] = [];
  const errors: string[] = [];
  if (!fs.existsSync(dir)) return { agents, errors };

  let entries: fs.Dirent[];
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch (err) {
    errors.push(`Cannot read ${dir}: ${(err as Error).message}`);
    return { agents, errors };
  }

  for (const entry of entries) {
    if (!entry.name.endsWith(".md")) continue;
    if (!entry.isFile() && !entry.isSymbolicLink()) continue;

    const filePath = path.join(dir, entry.name);
    const def = loadAgentFile(filePath, source);
    if (!def) {
      errors.push(`Skipping ${filePath}: invalid frontmatter (missing 'name' or 'description')`);
      continue;
    }
    agents.push(def);
  }
  return { agents, errors };
}

/**
 * Walk up from `cwd` looking for the nearest feature-agent
 * directory. The audit's active state dir is supplied so the
 * walker probes the resolved location first; legacy `.pi/agents/`
 * is checked last for backward compat with repos mid-migration.
 */
export function findNearestProjectAgentsDir(
  cwd: string,
  stateDir: string = ".pi/agentify",
): string | null {
  const dirsToCheck = [stateDir, ".pi/agentify"];
  let current = cwd;
  while (true) {
    for (const candidateBase of dirsToCheck) {
      const candidate = path.join(current, candidateBase, "agents");
      if (isDirectory(candidate)) return candidate;
    }
    const parent = path.dirname(current);
    if (parent === current) return null;
    current = parent;
  }
}

export interface DiscoveryResult {
  agents: AgentDefinition[];
  projectAgentsDir: string | null;
  errors: string[];
}

/**
 * Discover all agents. User-level (`<configDir>/agents/*.md`) +
 * project-level (`<cwd>/.pi/agents/*.md`). Project wins on conflict.
 */
export function discoverAgents(cwd: string, configDir = defaultConfigDir()): DiscoveryResult {
  const errors: string[] = [];

  const userDir = path.join(configDir, "agents");
  const projectAgentsDir = findNearestProjectAgentsDir(cwd);

  const userResult = loadAgentsFromDir(userDir, "user");
  const projectResult = projectAgentsDir
    ? loadAgentsFromDir(projectAgentsDir, "project")
    : { agents: [], errors: [] };

  errors.push(...userResult.errors, ...projectResult.errors);

  // Project overrides user with the same name.
  const map = new Map<string, AgentDefinition>();
  for (const a of userResult.agents) map.set(a.name, a);
  for (const a of projectResult.agents) map.set(a.name, a);

  return {
    agents: Array.from(map.values()),
    projectAgentsDir,
    errors,
  };
}

/**
 * Look up an agent by name in a registry. Returns null if not
 * found. The orchestrator's `create_agent` tool uses this to
 * resolve `subagent_template: "<name>"`.
 */
export function resolveTemplate(name: string, registry: AgentDefinition[]): AgentDefinition | null {
  return registry.find((a) => a.name === name) ?? null;
}

/**
 * Format the registry for inclusion in the orchestrator's system
 * prompt. Returns a compact Markdown table the LLM can scan.
 */
export function formatRegistryForPrompt(registry: AgentDefinition[]): string {
  if (registry.length === 0) {
    return "(no sub-agent templates registered)";
  }
  const rows = registry.map((a) => {
    const tools = a.tools.length > 0 ? a.tools.join(",") : "(read-only)";
    const model = a.model === "inherit" ? "(inherit)" : a.model;
    return `| \`${a.name}\` | ${truncate(a.description, 60)} | ${tools} | ${model} |`;
  });
  return [
    "| name | description | tools | model |",
    "|------|-------------|-------|-------|",
    ...rows,
  ].join("\n");
}

function truncate(s: string, max: number): string {
  if (s.length <= max) return s;
  return s.slice(0, max - 1) + "…";
}

/**
 * The SubagentRegistry class — wraps `discoverAgents` + a lookup
 * map. The orchestrator instantiates one and reuses it for the
 * lifetime of the orchestrator session.
 */
export class SubagentRegistry {
  private readonly byName: Map<string, AgentDefinition>;
  public readonly errors: string[];
  public readonly projectAgentsDir: string | null;

  constructor(agents: AgentDefinition[], projectAgentsDir: string | null, errors: string[]) {
    this.byName = new Map(agents.map((a) => [a.name, a]));
    this.errors = errors;
    this.projectAgentsDir = projectAgentsDir;
  }

  static fromCwd(cwd: string, configDir = defaultConfigDir()): SubagentRegistry {
    const result = discoverAgents(cwd, configDir);
    return new SubagentRegistry(result.agents, result.projectAgentsDir, result.errors);
  }

  list(): AgentDefinition[] {
    return Array.from(this.byName.values());
  }

  get(name: string): AgentDefinition | null {
    return this.byName.get(name) ?? null;
  }

  has(name: string): boolean {
    return this.byName.has(name);
  }

  formatForPrompt(): string {
    return formatRegistryForPrompt(this.list());
  }
}
